pipeline:
    name: NonMainPipeline
    identifier: NonMainPipeline
    projectIdentifier: RajathaTest
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: GitHubRajatha
                build: <+input>
    stages:
        - stage:
              name: adxas
              identifier: adxas
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.CItestK8sConnectorgjCxzubHye
                          namespace: sfsdfdsf
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: asdfsdf
                                identifier: asdfsdf
                                spec:
                                    connectorRef: account.testDockerConnectorjvBYBoPZnb
                                    image: alpine
                                    shell: Sh
                                    command: <+input>
