pipeline:
    name: TestappPipelineRemote
    identifier: TestappPipelineRemote
    projectIdentifier: RajathaDemo
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stg1
              identifier: stg1
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: RajathaK8
                          namespace: rajatha-pr-demo
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: step1
                                identifier: step1
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        echo testapp
                                        echo <+codebase.targetBranch>
                                        echo <+codebase.sourceBranch>
                                        echo <+codebase.repoUrl>
                                        echo 402pm
        - stage:
              name: stg2
              identifier: stg2
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: stg1
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: step2
                                identifier: step2
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo stage2
